
Red Snapper Video Index Using Delta GLM
========


```{r prelim,echo=FALSE,message=FALSE, warning=FALSE,error=FALSE}
rm(list=ls(all=TRUE)) 
graphics.off()
windows(record=T)
setwd ("\\\\CCFHR-S-1534090\\popdyn1\\SEDAR\\SEDAR 41\\SEFISIndices\\S41RGIT")
library(MASS)
library(doBy)
library(statmod)
library(Hmisc)
library(pscl)
library(rjags)
library(superdiag)
library(mcmcplots)
library(ggmcmc)
expit=function(x){1/(1+exp(-x))}

```

```{r ReadData, echo=FALSE,message=FALSE, warning=FALSE,error=FALSE}
 # Read in Red Snapper Data
rs=read.csv("\\\\CCFHR-S-1534090\\popdyn1\\SEDAR\\SEDAR 41\\SEFISIndices\\ConfData\\RedSnapGLMData.csv")#;head(rs)
````

```{r ConditionData, echo=FALSE,message=FALSE, warning=FALSE}
# Full data subsetting: 
rs <- rs[rs$Station_Type!="Recon",]                # remove recon stations
rs <- rs[rs$A.Video.Readable == "Yes",]         # remove invalid videos
rs <- subset(rs, rs$Start_Depth > 0)                  # remove NA in depth
rs <- subset(rs, rs$Start_Depth < 100)              # remove < 100 m deep
rs <- subset(rs, rs$LastOfTemp > 0)                 # remove blank water temps
rs <- subset(rs, rs$Turbidity != "Unknown")    # remove unknown turbidity values
rs <- subset(rs, rs$No.Readable.Frames ==41)    # remove zero readable frames

#Eliminate unnecessary columns
dat=subset(rs,select=c(MC_Lutjanus.campechanus,No.Readable.Frames,Year,Turbidity,Current_Direction,Current_Magnitude,Substrate_Cat,Relief,Size,Biotic_Density_Cat,Biotic_Type,Biotic_Height,Start_Depth,Julian,Start_Latitude,LastOfTemp,TOD))
orgnames=names(dat)

sumcount=round(dat$MC_Lutjanus.campechanus*rs$No.Readable.Frames,0)
dat$MC_Lutjanus.campechanus=sumcount

#rename to short names
names(dat)=c('fishseen','frames','y','wc','cd','cm','sc','sr','ss','bd','bt','bh','d','t','lat','temp','tod')#;head(dat)

#replace NA in the cpue with 0
dat$fishseen[is.na(dat$fishseen)]=0

#rescale frames
#dat$frames=dat$frames/41
#dat$frames=log(dat$frames)
#now categorize the continuous variables
#depth
hist(dat$d,breaks=seq(10,110,by=5))
summary(dat$d)
#temp=cut(dat$d,breaks=c(14,25,41,52,115),labels=FALSE)#;temp;table(temp)
#temp=cut(dat$d,2,breaks=c(0,as.numeric(summary(dat$d))[-c(1,4)]),labels=FALSE);temp;table(temp)
temp=cut(dat$d,2,breaks=quantile(dat$d),labels=FALSE)#;temp;table(temp)
dat$d=temp

#latitude
hist(dat$lat,breaks=seq(27,36,by=0.25))
summary(dat$lat)
#temp=cut(dat$lat,breaks=c(27,29.75,31.25,32.75,34,35.25),labels=FALSE)#;temp;table(temp)
#temp=cut(dat$lat,2,breaks=c(0,as.numeric(summary(dat$lat))[-c(1,4)]),labels=FALSE);temp;table(temp)
temp=cut(dat$lat,2,breaks=quantile(dat$lat),labels=FALSE)#;temp;table(temp)
dat$lat=temp

#day of year (t)
hist(dat$t,breaks=seq(110,305,by=5))
summary(dat$t)
#temp=cut(dat$t,breaks=c(##,##,##,##,##,##),labels=FALSE)#;temp;table(temp)
#temp=cut(dat$t,2,breaks=c(0,as.numeric(summary(dat$t))[-c(1,4)]),labels=FALSE);temp;table(temp)
temp=cut(dat$t,2,breaks=quantile(dat$t),labels=FALSE)#;temp;table(temp)
dat$t=temp

#water temperature (temp)
hist(dat$temp,breaks=seq(12.25,29.25,by=0.25))
summary(dat$temp)
#temp=cut(dat$t,breaks=c(##,##,##,##,##,##),labels=FALSE)#;temp;table(temp)
#temp=cut(dat$temp,2,breaks=c(0,as.numeric(summary(dat$temp))[-c(1,4)]),labels=FALSE);temp;table(temp)
temp=cut(dat$temp,2,breaks=quantile(dat$temp),labels=FALSE)#;temp;table(temp)
dat$temp=temp

#time of day (tod)
hist(dat$tod,breaks=seq(0.4,0.95,by=0.025))
summary(dat$tod)
#temp=cut(dat$tod,breaks=c(##,##,##,##,##,##),labels=FALSE)#;temp;table(temp)
#temp=cut(dat$tod,2,breaks=c(0,as.numeric(summary(dat$tod))[-c(1,4)]),labels=FALSE);temp;table(temp)
temp=cut(dat$tod,2,breaks=quantile(dat$tod),labels=FALSE)#;temp;table(temp)
dat$tod=temp

#Factorize variables
dat$y=factor(dat$y)
dat$d=factor(dat$d)
dat$lat=factor(dat$lat)
dat$t=factor(dat$t)
dat$temp=factor(dat$temp)
dat$tod=factor(dat$tod)

#get rid of unused factors for dat$wc
dat$wc=factor(dat$wc)

plot.design(fishseen~y + wc + cd + cm ,data=dat)
plot.design(fishseen~y + wc + sc + sr + ss ,data=dat)
plot.design(fishseen~y + wc + bd + bt + bh ,data=dat)
plot.design(fishseen~y + wc +  d + t + lat + temp + tod,data=dat)
plot.design(fishseen~y + wc + cd + cm + sc + sr + ss + bd + bt + bh + d + t + lat + temp + tod,data=dat)

```

**So this bit allows variable selection of each of the model types**
```{r jags}

modelFilename = "LogPoisLink"
cat("
    model {
    #First set up the prior Weight Parameters

    for(i in 1:54){
    w[i] ~ dbern(.5)
    }


    #Priors parameters

    # For the non zero infl part

    for(i in 1:28){
    alph[i] ~ dt(0,pow(1.566267,-2),7.63179)#dnorm(0,.1)
    }

    # For the non zero infl part
    for(i in 1:28){
    bet[i] ~ dnorm(0,.01)
    }

    zepitau~dgamma(.1,.1)

    #model
    for (i in 1:samp){



    log.ypred[i] <- bet[1]+
    w[1]*bet[2]*y2011[i]+w[2]*bet[3]*y2012[i]+
    w[3]*bet[4]*wc.1[i]+w[4]*bet[5]*wc.2[i]+
    w[5]*bet[6]*cd.s[i]+w[6]*bet[7]*cd.t[i]+w[7]*bet[8]*cd.u[i]+
    w[8]*bet[9]*sc.l[i]+w[9]*bet[10]*sc.m[i]+w[10]*bet[11]*sc.n[i]+w[11]*bet[12]*sc.u[i]+
    w[12]*bet[13]*bd.l[i]+w[13]*bet[14]*bd.m[i]+w[14]*bet[15]*bd.n[i]+w[15]*bet[16]*bd.u[i]+
    w[16]*bet[17]*d.2[i]+w[17]*bet[18]*d.3[i]+w[18]*bet[19]*d.4[i]+
    w[19]*bet[20]*t.2[i]+w[20]*bet[21]*t.3[i]+w[21]*bet[22]*t.4[i]+
    w[22]*bet[23]*lat.2[i]+w[23]*bet[24]*lat.3[i]+w[24]*bet[25]*lat.4[i]+
    w[25]*bet[26]*temp.2[i]+w[26]*bet[27]*temp.3[i]+w[27]*bet[28]*temp.4[i] +
    zepi[i]

    zepi[i] ~ dnorm(0,zepitau)

    #logit.psi[i] <- alph[1]

    #Use This bit for the psi-lambda link
    #logit.psi[i] <- alph[1]+w[28]*alph[2]*log.ypred[i]


    ###Use this bit to have the global model for zero inflation
    logit.psi[i] <- alph[1]+
    w[28]*alph[2]*y2011[i]+w[29]*alph[3]*y2012[i]+
    w[30]*alph[4]*wc.1[i]+w[31]*alph[5]*wc.2[i]+
    w[32]*alph[6]*cd.s[i]+w[33]*alph[7]*cd.t[i]+w[34]*alph[8]*cd.u[i]+
    w[35]*alph[9]*sc.l[i]+w[36]*alph[10]*sc.m[i]+w[37]*alph[11]*sc.n[i]+w[38]*alph[12]*sc.u[i]+
    w[39]*alph[13]*bd.l[i]+w[40]*alph[14]*bd.m[i]+w[41]*alph[15]*bd.n[i]+w[42]*alph[16]*bd.u[i]+
    w[43]*alph[17]*d.2[i]+w[44]*alph[18]*d.3[i]+w[45]*alph[19]*d.4[i]+
    w[46]*alph[20]*t.2[i]+w[47]*alph[21]*t.3[i]+w[48]*alph[22]*t.4[i]+
    w[49]*alph[23]*lat.2[i]+w[50]*alph[24]*lat.3[i]+w[51]*alph[25]*lat.4[i]+
    w[52]*alph[26]*temp.2[i]+w[53]*alph[27]*temp.3[i]+w[54]*alph[28]*temp.4[i]




    psi[i]<-exp(logit.psi[i])/(1+exp(-logit.psi[i]))
    ypred[i]<-exp(log.ypred[i])
    z[i] ~ dbern(psi[i])
    lambda[i] <- z[i]*ypred[i]
    fishseen[i] ~ dpois(lambda[i])
    }
    }

    ", fill=TRUE, file=modelFilename)


#use this line to make a covariate with random values
#dat$d=sample(c("1","2","3","4"),dim(dat)[1],replace=T)
#################################


jags.data = list(fishseen=dat$fishseen,y2011=as.numeric(dat$y=='2011'), y2012=as.numeric(dat$y=='2012'),
                 wc.1=as.numeric(dat$wc==1),wc.2=as.numeric(dat$wc==2),
                 cd.s=as.numeric(dat$cd=="Sideways"),cd.t=as.numeric(dat$cd=="Towards"),cd.u=as.numeric(dat$cd=="Unknown"),
                 sc.l=as.numeric(dat$sc=="Low"),sc.m=as.numeric(dat$sc=="Moderate"),sc.n=as.numeric(dat$sc=="None"),sc.u=as.numeric(dat$sc=="Unknown"),
                 bd.l=as.numeric(dat$bd=="Low"),bd.m=as.numeric(dat$bd=="Moderate"),bd.n=as.numeric(dat$bd=="None"),bd.u=as.numeric(dat$bd=="Unknown"),
                 d.2=as.numeric(dat$d=="2"),d.3=as.numeric(dat$d=="3"),d.4=as.numeric(dat$d=="4"),
                 t.2=as.numeric(dat$t=="2"),t.3=as.numeric(dat$t=="3"),t.4=as.numeric(dat$t=="4"),
                 lat.2=as.numeric(dat$lat=="2"),lat.3=as.numeric(dat$lat=="3"),lat.4=as.numeric(dat$lat=="4"),
                 temp.2=as.numeric(dat$temp=="2"),temp.3=as.numeric(dat$temp=="3"),temp.4=as.numeric(dat$temp=="4"),
                 samp=dim(dat)[1])

jags.inits = function(){list(bet = rnorm(28,0,.15),alph=rnorm(28,0,.01),z=rep(1,dim(dat)[1]),w=rep(1,54))}
jags.parms = c('w','bet','alph','zepitau')#,'zepi')

jinits=jags.inits()
jmod = jags.model(file=modelFilename, data=jags.data, inits = jags.inits(),n.chains=3, n.adapt=1000)
#jmod = jags.model(file=modelFilename, data=jags.data,n.chains=3, n.adapt=100)   #inits = jags.inits(),
update(jmod, n.iter=10000, by=10, progress.bar='text')
post = coda.samples(jmod, jags.parms, n.iter=50000, thin=10)
dicsam=dic.samples(jmod, 1000, "popt")
mypost = as.matrix(post, chain=F)
plot(post)
summary(post)

 head(mypost,1)
  alpha = mypost[,1:28]
  beta = mypost[,29:56]
  w = mypost[,57:(57+53)]
  epitaupost = mypost[,dim(mypost)[2]]
#------------------------------------------------------------------------------#
#    model probs
#------------------------------------------------------------------------------#
models = as.matrix(table(paste(w[,1],w[,2],w[,3],w[,4],w[,5],w[,6],w[,7],w[,8],
                               w[,9],w[,10],w[,11],w[,12],w[,13],w[,14],w[,15],
                               w[,16],w[,17],w[,18],w[,19],w[,20],w[,21],w[,22],
                               w[,23],w[,24],w[,25],w[,26],w[,27],w[,28],
                               w[,29],w[,30],w[,31],w[,32],w[,33],w[,34],
                               w[,35],w[,36],w[,37],w[,38],w[,39],w[,40],
                               w[,41],w[,42],w[,43],w[,44],w[,45],w[,46],
                               w[,47],w[,48],w[,49],w[,50],w[,51],w[,52],
                               w[,53],w[,54],
                                sep="")))/dim(w)[[1]]

#This identifies the top 10 models and their probabilities
modprobs = as.matrix(as.matrix(models[order(models[,1],decreasing = T),])[1:15,])
#------------------------------------------------------------------------------#
#    Summary statistics
#------------------------------------------------------------------------------#
bet=beta[,2:28]
parmas = bet*w[,1:27]
rm(res)
res=t(rbind(mean=colMeans(parmas),
sd=apply(parmas,2,sd),
apply(parmas,2,quantile,c(0.025,0.975),na.rm=T),
probs=colMeans(w[,1:27])))
beta.int=cbind(beta[,1:2])
res=rbind(t(rbind(mean=colMeans(beta.int),sd=apply(beta.int,2,sd),apply(beta.int,2,quantile,c(0.025,0.975),na.rm=T),c(1,1))),res)[-2,]
alph=alpha[,2:28]*w[,28:54]
rm(temp)
temp=t(rbind(mean=colMeans(alph),sd=apply(alph,2,sd),apply(alph,2,quantile,c(0.025,0.975),na.rm=T),probs=colMeans(w[,28:54])))
tempx=c(mean=mean(alpha[,1]),sd=sd(alpha[,1]),quantile(alpha[,1],c(0.025,0.975),na.rm=T),1)
temp=rbind(tempx,temp)
res=rbind(res,temp)

save.image("//CCFHR-S-1534090/popdyn1/SEDAR/SEDAR 41/SEFISIndices/S41RGIT/LogPoisNotLinked.RData")

```

```{r makeindex, echo=TRUE,message=TRUE, warning=TRUE,error=TRUE}


#not sure if this is any good
goodparms=cbind(beta[,1],parmas[,res[2:28,5]>=0.5],alpha[,1],alph[,res[30:56,5]>=0.5])
beta*

new.dat=cbind(y2011=as.numeric(dat$y=='2011'), y2012=as.numeric(dat$y=='2012'),
wc.1=as.numeric(dat$wc==1),wc.2=as.numeric(dat$wc==2),
cd.s=as.numeric(dat$cd=="Sideways"),cd.t=as.numeric(dat$cd=="Towards"),cd.u=as.numeric(dat$cd=="Unknown"),
sc.l=as.numeric(dat$sc=="Low"),sc.m=as.numeric(dat$sc=="Moderate"),sc.n=as.numeric(dat$sc=="None"),sc.u=as.numeric(dat$sc=="Unknown"),
bd.l=as.numeric(dat$bd=="Low"),bd.m=as.numeric(dat$bd=="Moderate"),bd.n=as.numeric(dat$bd=="None"),bd.u=as.numeric(dat$bd=="Unknown"),
d.2=as.numeric(dat$d=="2"),d.3=as.numeric(dat$d=="3"),d.4=as.numeric(dat$d=="4"),
t.2=as.numeric(dat$t=="2"),t.3=as.numeric(dat$t=="3"),t.4=as.numeric(dat$t=="4"),
lat.2=as.numeric(dat$lat=="2"),lat.3=as.numeric(dat$lat=="3"),lat.4=as.numeric(dat$lat=="4"),
temp.2=as.numeric(dat$temp=="2"),temp.3=as.numeric(dat$temp=="3"),temp.4=as.numeric(dat$temp=="4"))

loglam=rowSums(res[2:28,1]*new.dat)
loglam=res[1,1]+loglam
lam=exp(loglam)
#hist(lam)

logitpi=rowSums(res[30:56,1]*new.dat)
logitpi=res[29,1]+logitpi
pi=expit(logitpi)
#hist(pi)

exptcount=pi*lam
bern=function(x){rbinom(n=1,size=,1,prob=x)}
exptcount=sapply(pi,bern)*lam
#hist(exptcount)
hist(dat$fishseen,breaks=0:max(dat$fishseen),freq=T,right=TRUE,xlab='Aggregate Fish Counted', main='NB')  
d3=hist(exptcount,breaks=0:max(dat$fishseen),plot=FALSE)
lines(seq(0.5,max(dat$fishseen),by=1),d3$counts, col="blue",type='l')      
hist(dat$fishseen,breaks=0:max(dat$fishseen),freq=T,right=TRUE,xlab='Aggregate Fish Counted', main='NB',ylim=c(0,50))  
lines(seq(0.5,max(dat$fishseen),by=1),d3$counts, col="blue",type='l')      




#counts=matrix(rep(rep(1,dim(new.dat)[1],dim(beta)[1])),dim(new.dat)[1],dim(beta)[1])
##for(i in 1:dim(new.dat)[1]){
  #for(j in 1:dim(beta)[1]){
  #  counts[i,j]=exp(beta[j,1]+sum(parmas[j,]*new.dat[i,]))
   # }
  #}



```

